modLoader = "javafml"
loaderVersion = "[${minFMLVersion},)"
issueTrackerURL = "${modIssueUrl}"
license = "${modLicense}"

[[mods]]
    modId="${modId}"
    displayName="${modName}"
    description="${modDescription}"
    version="${modVersion}"
    authors="${modAuthor}"
    logoFile="${modLogoFile}"
    logoBlur=false
    displayURL="${modPageUrl}"
    displayTest="${modForgeDisplayTest}"

[[dependencies.${modId}]]
    modId = "forge"
    mandatory = true
    versionRange = "[${minFMLVersion},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${modId}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[${minMinecraftVersion},${nextMinecraftVersion})"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${modId}]]
    modId = "architectury"
    mandatory = true
    versionRange = "[${architecturyVersion},)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.${modId}]]
    modId="configured"
    mandatory=true
    versionRange="[${configuredForgeVersion},)"
    ordering="NONE"
    side="BOTH"

[modproperties.${modId}]
    catalogueImageIcon="${modIconFile}"
    catalogueItemIcon="${modIconItem}"
    configuredConfigs=[ "${configEntryPoint}" ]
    configuredBackground="${configuredBackgroundFile}"
